# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/uni/MCP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/uni/MCP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/uni/MCP/CMakeFiles /home/chris/uni/MCP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/uni/MCP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MY_MCP

# Build rule for target.
MY_MCP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MY_MCP
.PHONY : MY_MCP

# fast build rule for target.
MY_MCP/fast:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/build
.PHONY : MY_MCP/fast

MY_MCP.o: MY_MCP.cpp.o

.PHONY : MY_MCP.o

# target to build an object file
MY_MCP.cpp.o:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/MY_MCP.cpp.o
.PHONY : MY_MCP.cpp.o

MY_MCP.i: MY_MCP.cpp.i

.PHONY : MY_MCP.i

# target to preprocess a source file
MY_MCP.cpp.i:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/MY_MCP.cpp.i
.PHONY : MY_MCP.cpp.i

MY_MCP.s: MY_MCP.cpp.s

.PHONY : MY_MCP.s

# target to generate assembly for a file
MY_MCP.cpp.s:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/MY_MCP.cpp.s
.PHONY : MY_MCP.cpp.s

costs.o: costs.cpp.o

.PHONY : costs.o

# target to build an object file
costs.cpp.o:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/costs.cpp.o
.PHONY : costs.cpp.o

costs.i: costs.cpp.i

.PHONY : costs.i

# target to preprocess a source file
costs.cpp.i:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/costs.cpp.i
.PHONY : costs.cpp.i

costs.s: costs.cpp.s

.PHONY : costs.s

# target to generate assembly for a file
costs.cpp.s:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/costs.cpp.s
.PHONY : costs.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/MY_MCP.dir/build.make CMakeFiles/MY_MCP.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... MY_MCP"
	@echo "... edit_cache"
	@echo "... MY_MCP.o"
	@echo "... MY_MCP.i"
	@echo "... MY_MCP.s"
	@echo "... costs.o"
	@echo "... costs.i"
	@echo "... costs.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

